config/routes.rb
Rails.application.routes.draw do
  get 'todos', to: 'todos#index'
  get 'todos/new'
  post 'todos', to: 'todos#create'
  get 'todos/:id', to: 'todos#show', as: :todo
  get 'todos/:id/edit', to: 'todos#edit', as: :edit_todo
  patch 'todos/:id', to: 'todos#update'
  delete 'todos/:id', to: 'todos#destroy'
  get 'todos/:id/complete', to: 'todos#complete', as: :complete_todo
  get 'list', to: 'todos#list', as: :list_todo
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  def index
    @todos = Todo.all
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    if @todo.save
    redirect_to todos_path
    else
      redirect_to todos_new_path, notice:"Debes introducir una tarea"
    end
  end

  def show
    @todo = Todo.find(params[:id])
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def update
    @todo = Todo.find(params[:id])
    @todo.update(todo_params)
    redirect_to todos_path
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy
    redirect_to todos_path
  end

  def complete
    @todo = Todo.find(params[:id])
    @todo.completed = true
    @todo.save
    redirect_to todos_path
  end

  def list
    @todos = Todo.all
  end

  private
  def todo_params
    params.require(:todo). permit(:description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/_navbar.html.erb
<!-- Nav Bar -->
<nav class="navbar navbar-expand-lg navbar navbar-dark bg-primary fixed-top ">
  <a class="navbar-brand" href="<%= todos_path %>">ToDo App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%= todos_path %>">INDEX <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= list_todo_path %>">LISTA</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= todos_new_path %>">CREAR</a>
      </li>
    </ul>
  </div>
</nav>
<!-- Nav Bar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <!-- CDN Bootstrap-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container my-5 py-5">
      <%= yield %>
    </div>

    <!-- CDN JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with model: @todo, local: true do |t| %>
<div class="form-group">
  <%= t.label :description, "Descripción" %>
  <%= t.text_field :description, class: 'form-group', placeholder: 'Ej: Ir a comprar pan' %>
</div>
  <%= t.submit "Agregar tarea", class: 'form-group' %>
<%= link_to "Volver", todos_path %>
<% end %>

app/views/todos/edit.html.erb
<h1>Edición de una nueva lista de "ToDo"</h1>

<%= render 'todos/form' %>

app/views/todos/index.html.erb
<h1>Mi lista de tareas</h1>
<br>
<%= link_to "Agregar nueva tarea", todos_new_path, class: 'btn btn-primary' %>
<%= link_to "Ver listado de tareas", list_todo_path, class: 'btn btn-primary' %>
<br><br><br>
<% @todos.each do |todo| %>
<div class="card card-body bg-light">
  <p><%= todo.description %></p>
  <%= link_to "Ver tarea", todo, class: 'btn btn-primary' %>
  <%= link_to "Editar tarea", edit_todo_path(todo), class: 'btn btn-info' %>
  <%= link_to "Eliminar tarea", todo, method: :delete, class: 'btn btn-danger' %>
<div>
<% if todo.completed == true %>
<p>Realizada</p>
<% else %>
<%= link_to "Check", complete_todo_path(todo), class: 'btn btn-success' %>
<% end %>
</div>
</div>
<% end %>

app/views/todos/list.html.erb
<h1>Listado de tareas</h1>

<div class="container">
  <div class="row">

    <div class="col-6"><h3>No completadas</h3>
      <% @todos.each do |t| %>
        <% if t.completed != true %>
        <div> <%= t.description %> </div>
        <% end %>
      <% end %>
    </div>

    <div class="col-6"><h3>Completadas</h3>
      <% @todos.each do |t| %>
        <% if t.completed == true %>
        <div> <%= t.description %> </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/todos/new.html.erb
<h1>Creación de una nueva tarea</h1>

<%= notice %>

<%= render 'todos/form' %>

app/views/todos/show.html.erb
<h1> Estado de mi lista de tareas </h1>
<h2> Tarea: <%= @todo.description %> </h2>
<p> <%= @todo.completed %> </p>
<p> <%= @todo.created_at %> </p>

<%= link_to "Volver", todos_path %>